name: Docker Hub Noetic build

on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "carma-system-*"
  workflow_dispatch:

jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      file: ./noetic/Dockerfile
      tag_name_suffix: noetic
