name: Docker Noetic build

on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      file: ./noetic/Dockerfile
      tag_name_suffix: noetic
      replace_suffix: true # TODO: remove after develop-humble branch is merged to develop
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
