name: Docker Hub build

on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "carma-system-*"
jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@fix-dockerhub-action-to-pass-dockerfile-org-and-tag-args
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}