name: Docker Noetic build

on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@arc-199-support-different-suffix
    with:
      file: ./noetic/Dockerfile
      tag_name_suffix: noetic
      replace_suffix: true
